# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macOS-10.13'

steps:
- task: Xcode@5
  inputs:
    displayName: 'Build'
    actions: 'build'
    scheme: 'swift-helloworld'
    sdk: 'iphoneos'
    configuration: 'Debug'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: '10' # Options: 8, 9, 10, default, specifyPath
- task: Xcode@5
  displayName: 'Running XCTest/XCUITest'
  inputs:
    actions: 'test'
    scheme: '$(scheme)'
    sdk: 'iphonesimulator'
    configuration: 'swift-helloworld'
    xcodeVersion: '10' # Options: 8, 9, default, specifyPath
    packageApp: false
    xcWorkspacePath: 'swift-helloworld.xcodeproj'
    destinationSimulators: 'iPhone 7'
    destinationTypeOption: 'simulators'
    destinationPlatformOption: 'iOS'
    useXcpretty: true
    publishJUnitResults: 'build/reports/<span class="skimlinks-unlinked">junit.xml</span>'
